// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//    {"TargetFramework":"NetStandard","NameSpace":"TechNoir.Data.Entity.Edmx.Serialization","Properties":{"AutomaticProperties":true},"XmlAttribute":{"Enabled":true},"ClassParams":{"GenerateInSeparateFiles":true},"Serialization":{"ShouldSerialize":{},"XmlSerializerEvent":{},"XmlOutput":{},"JsonOutput":{},"Enabled":true},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
#pragma warning restore
