// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace TechNoir.Data.Entity.Edmx.Serialization
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://schemas.technoir.net/ado/edm/Common.xsd")]
public enum TMultiplicity
{
    [XmlEnumAttribute("0..1")]
    Item01,
    [XmlEnumAttribute("1")]
    Item1,
    [XmlEnumAttribute("*")]
    Item,
}
}
#pragma warning restore
